name: fast-deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          repository: bcggxx/android_kernel_xiaomi_sm8250
          ref: android16-aptusitu
          fetch-depth: 1
          token: ${{ secrets.GH_TOKEN }}
      - run: |
          git config --global user.name "cctv77"
          git config --global user.email "222525559+cctv77@users.noreply.github.com"
          find . -type f ! -path "./.git/*" -exec sed -i "s/bcggxx/cctv77/g" {} \;
          find . -type f ! -path "./.git/*" -exec sed -i "s/aparttusitu/cctv77/g" {} \;
          find . -type f ! -path "./.git/*" -exec sed -i "s/android_kernel_xiaomi_sm8250/Fraud/g" {} \;
          git add .
          git commit -m "init"
          git checkout -b k40-android16-sync
          git push -u origin k40-android16-sync --force
